package com.prajjwal.UrbanBites.enums;

public enum NotificationType {
    ACCOUNT_REGISTERED,
    LOGIN_ALERT,
    ORDER_CONFIRMED,
    ORDER_ACCEPTED_BY_RESTAURANT,
    ORDER_PREPARING,
    ORDER_READY_FOR_PICKUP,
    ORDER_OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    ORDER_OWNER_ACTION_REQUIRED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    REFUND_PROCESSED,
    DELIVERY_NO_AGENT_AVAILABLE,
    PARTNER_APPROVAL_APPROVED,
    PARTNER_APPROVAL_REJECTED,
    RESTAURANT_APPROVAL_APPROVED,
    RESTAURANT_APPROVAL_REJECTED,
    DELIVERY_AGENT_APPROVAL_APPROVED,
    DELIVERY_AGENT_APPROVAL_REJECTED
}

